Ingredient.create(name: "Sugar")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Gim")
Ingredient.create(name: "Whisky")
Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Juice")

